apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  namespace: applications
  annotations: {}
type: Opaque
data:
  {{- if not (empty .Values.auth.database) }}
  mysql-database: {{ .Values.auth.database | b64enc | quote }}
  {{- else }}
  mysql-database: {{ required "A MySQL Database Name is required!" .Values.auth.database }}
  {{- end }}
  {{- if not (empty .Values.auth.username) }}
  mysql-username: {{ .Values.auth.username | b64enc | quote }}
  {{- else }}
  mysql-username: {{ required "A MySQL Database Username is required!" .Values.auth.username }}
  {{- end }}
  {{- if not (empty .Values.auth.password) }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ required "A MySQL Database Password is required!" .Values.auth.password }}
  {{- end }}
